# Generated by Django 2.2 on 2019-04-26 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=20)),
                ('post_Article', models.TextField()),
                ('post_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_auther', models.CharField(max_length=20)),
            ],
        ),
    ]
