# Generated by Django 2.2 on 2019-04-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_images',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
