# Generated by Django 2.2 on 2019-04-26 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='email',
            new_name='e_mail',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='fnam',
            new_name='f_name',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='lnam',
            new_name='l_name',
        ),
    ]
