# Generated by Django 2.2 on 2019-05-02 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190426_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('contacttime', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.EmailField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('body', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='post',
            new_name='posts',
        ),
    ]
