# Generated by Django 2.2 on 2019-05-02 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190502_1801'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
