# Generated by Django 2.2 on 2019-05-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190502_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='menutabs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menutabs_title', models.CharField(max_length=40)),
            ],
        ),
    ]
