# Generated by Django 2.2 on 2019-05-10 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_menutab_menutab_adres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menutab',
            old_name='menutab_adres',
            new_name='menu_adres',
        ),
        migrations.RenameField(
            model_name='menutab',
            old_name='menutab_title',
            new_name='menu_title',
        ),
    ]
