# Generated by Django 2.1.1 on 2018-09-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mamjow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='age',
            field=models.IntegerField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
